### PR TITLE
Upgrade Bolt driver to 1.5.0

### PR DESCRIPTION
**Pull request by fbiville**
I could not run the performance tests:

```
java.lang.IllegalStateException: failed to create a child event loop
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at org.neo4j.driver.internal.shaded.io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:52)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:87)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:82)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:63)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:51)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:43)
	at org.neo4j.driver.internal.async.EventLoopGroupFactory$DriverEventLoopGroup.<init>(EventLoopGroupFactory.java:117)
	at org.neo4j.driver.internal.async.EventLoopGroupFactory.newEventLoopGroup(EventLoopGroupFactory.java:78)
	at org.neo4j.driver.internal.async.BootstrapFactory.newBootstrap(BootstrapFactory.java:33)
	at org.neo4j.driver.internal.DriverFactory.createBootstrap(DriverFactory.java:244)
	at org.neo4j.driver.internal.DriverFactory.newInstance(DriverFactory.java:76)
	at org.neo4j.driver.v1.GraphDatabase.driver(GraphDatabase.java:136)
	at org.neo4j.driver.v1.GraphDatabase.driver(GraphDatabase.java:119)
	at org.neo4j.driver.v1.GraphDatabase.driver(GraphDatabase.java:94)
	at org.neo4j.jdbc.bolt.SamplePT.testSimpleQueryBoltDriver(SamplePT.java:101)
	at org.neo4j.jdbc.bolt.generated.SamplePT_testSimpleQueryBoltDriver_jmhTest.testSimpleQueryBoltDriver_avgt_jmhStub(SamplePT_testSimpleQueryBoltDriver_jmhTest.java:191)
	at org.neo4j.jdbc.bolt.generated.SamplePT_testSimpleQueryBoltDriver_jmhTest.testSimpleQueryBoltDriver_AverageTime(SamplePT_testSimpleQueryBoltDriver_jmhTest.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:453)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:437)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.neo4j.driver.internal.shaded.io.netty.channel.ChannelException: failed to open a new selector
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:175)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:149)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	... 30 more
Caused by: java.io.IOException: Too many open files in system
	at sun.nio.ch.IOUtil.makePipe(Native Method)
	at sun.nio.ch.KQueueSelectorImpl.<init>(KQueueSelectorImpl.java:84)
	at sun.nio.ch.KQueueSelectorProvider.openSelector(KQueueSelectorProvider.java:42)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:173)
	... 34 more
```

### CODE REVIEW

**Comment by glaggia-larus** [comment]
This PR should be made against branch neo4j-contrib:3.2

I can't merge it to 3.1 because this commit will be lost in 3.2

**Review by glaggia-larus — CHANGES_REQUESTED** [review]
We need this to be made against neo4j-contrib:3.2

**Comment by fbiville** [comment]
OK, closing this one and reopening another one.

**Comment by fbiville** [comment]
Actually, not opening another one.
Is there a release date for what's in 3.2 branch?
Bolt driver @ version `1.4.5` should be enough.

**Comment by glaggia-larus** [comment]
It should be any days soon.

Then we might release a patch with bolt driver raised to 1.5

**Pull request closed without merging**
