### PR TITLE
resultset detection for prepared statements

### PR DESCRIPTION
**Pull request by inserpio**

### CODE REVIEW

**Comment by jexp** [comment]
Can you do the same for normal statements (`getMoreResults`)?

**Comment by jexp** [comment]
Hmm this misses the implementation for getMoreResults?

**Comment by jexp** [comment]
Don't we have a proper information somewhere if this is a statement returning data?

`this.statement.toLowerCase().contains("return")` is definitely not enough.

E.g. standalone procedure calls also return data.

**Comment by inserpio** [comment]
`getMoreResults` is fine as it's. Closing the cursor inside this method doesn't work. In fact, many tests fail if you do that. Also, I was wondering if it's correct to call `close` explicitly given that `ResultSet` is `AutoClosable`?

Second, testing "return" inside the string is, of course, undesirable and error-prone (we should at least check if the word is escaped and part of a real string).
Unfortunately, the only way to detect which kind of statement we have is to consume the `StatementResult` and check the `StatementType` (READ_ONLY, READ_WRITE, WRITE_ONLY, SCHEMA_WRITE): `StatementResult.consume.statementType`, but we clearly cannot consume it as it could be very large. Also we cannot `peek` the first record (not to move the cursor) as it would throw an exception for empty resultSets and we need to clearly distinguish between a statement without resultset (aka create statement) and a match that actually has a resultset which could be empty.

**Comment by inserpio** [comment]
Do we have something in APOC to do it better? Can't remember

**Pull request merged**
