### PR TITLE
[#128] Remove query escaping

### PR DESCRIPTION
**Pull request by fbiville**

### CODE REVIEW

**Comment by jexp** [comment]
@albertodelazzari why did we do this in the first place again?

**Comment by sim51** [comment]
Sorry, I don't remember the reason (if there is one ...). I assume it's due to some json serialization, but I have done some tests, and if I remove the `escapeQuery` method everything is working.

**Comment by fbiville** [comment]
Shall I remove the escaping entirely, then?

**Comment by jexp** [comment]
I think so, if no one remembers why we have it. 
Are there any failing tests if it is commented out?

**Comment by fbiville** [comment]
@jexp nope, PR updated

**Pull request merged**
