### PR TITLE
Reduce über-JAR size 📉

### PR DESCRIPTION
**Pull request by fbiville**
This goes from 37M to 7.6M!

### CODE REVIEW

**Comment by fbiville** [comment]
Tested locally with Neo4j Liquibase (changed the artifactId and version): it works fine.

**Comment by fbiville** [comment]
Waiting for @conker84 to greenlight this with APOC and Neo4j streams.

**Comment by conker84** [comment]
@fbiville I tried in streams and unfortunately with the trimmed jar the plugin doesn't start :(

**Review by conker84 — APPROVED** [review]

**Comment by fbiville** [comment]
> @fbiville I tried in streams and unfortunately with the trimmed jar the plugin doesn't start :(

oh no, what errors do you see?

**Comment by drraghavendra** [comment]
Optimize über-JAR size then for sure it will work I have tested as well @conker84 sir

**Comment by fbiville** [comment]
Let's close this for now.

**Pull request closed without merging**
