### PR TITLE
Relocate Jackson to shaded package

### LINKED ISSUE #321: JDBC driver should relocate shaded libraries
We've recently ran into an issue with fabric 8 client not being able to find jackson method:

```shell
Exception in thread "OkHttp Dispatcher" java.lang.NoSuchMethodError: 'com.fasterxml.jackson.core.util.JacksonFeatureSet com.fasterxml.jackson.core.JsonParser.getReadCapabilities()'
	at com.fasterxml.jackson.databind.DeserializationContext.<init>(DeserializationContext.java:211)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.<init>(DefaultDeserializationContext.java:50)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext$Impl.<init>(DefaultDeserializationContext.java:391)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext$Impl.createInstance(DefaultDeserializationContext.java:413)
	at com.fasterxml.jackson.databind.ObjectMapper.createDeserializationContext(ObjectMapper.java:4654)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4583)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3591)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:261)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:184)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:170)
	at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.readWatchEvent(AbstractWatchManager.java:200)
	at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.onMessage(AbstractWatchManager.java:225)
	at io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener.onMessage(WatcherWebSocketListener.java:93)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
After a lot of debugging, we found the `neo4j-jdbc-driver` is including it's own copy of jackson, which is out of date. This is a huge problem that is very hard to detect.

The correct way to shade libraries like this would be to [relocate the classes](https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html), this is what gRPC and other major libraries have done for many years.

Hope this helps others that are struggling with this same issue

### PR DESCRIPTION
**Pull request by martintreurnicht**
Resolves https://github.com/neo4j-contrib/neo4j-jdbc/issues/321

### CODE REVIEW

**Comment by conker84** [comment]
Hi @martintreurnicht and thanks for the contribution!

Can you please try just to exclude Jackson from the neo4j JDBC driver in your Maven/Gradle project before?

https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html
https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html

Relocation should be an extrema-ratio in very specific situations. Moreover, if we do for Jackson we need to do also for other third-party libraries that we use in the project.

I'm closing this for now please feel free to reopen in case transitive dependency exclusion is not a solution, in that case, please provide a reproducible example that will allow us to better understand the problem.

**Comment by martintreurnicht** [comment]
@conker84 The fix you suggested doesn't work because you're packaging all dependencies into a far jar essentially, the fix you suggested only works if you don't do that and actually pull these dependencies in transitively using maven/gradle, and yes you are correct, you should probably repackage all the third party libraries you're including in the fatjar, we haven't experienced issues with all the other dependencies but I'm sure someone has. It would probably be a good idea to switch to not creating a fatjar for the driver, but that isn't my call and is out of scope to this issue, I'm sure there is a reason why this was done this way, but not relocating these classes causes a huge amount of issues and completely breaks the dependency system in both maven and gradle

**Comment by fbiville** [comment]
@martintreurnicht you don't have to use the fat JAR though. The JDBC driver "flavors" (HTTP, Bolt) are also available as regular dependencies.

**Comment by martintreurnicht** [comment]
@fbiville Yeah sure, i understand that. The problem is, we're not pulling this driver in directly. It's being pulled in by https://github.com/liquibase/liquibase-neo4j. Really just feels like we're kicking the can down the road here though, repacking these libraries doesn't affect functionality at all, it just cleans up the classpath and allows your dependency graph to continue to work correctly. It's a pretty common pattern used by many big libraries out there, including gRPC. I'm not suggesting anything novel here, I'm just trying to fix a serious issue with your library. These shaded archives were originally intended to create distributions, similar to a WAR file, it's not supposed to be used as a dependency really, unless you shade it's dependencies

**Comment by martintreurnicht** [comment]
In my mind there is only 2 paths forward here:

1. The driver package removes the shaded plugin, and dependencies are pulled in transitively. Pros: Much easier to analyze the dependency graph, con: If you happen to have newer versions of these libraries in your project that is not backwards compatible, it will break the driver and you'll be forced to downgrade to a version compatible with the driver (which is anyway happening right now).
2. You repackage the shaded libraries so that the driver becomes an isolated system, where it's dependencies does not affect any external systems. Pros: reliable, Cons: larger binaries (this is already the case today)

Based on my analysis, the way it's done right now you get the cons from both of these approaches, and non of the pros

**Comment by fbiville** [comment]
@martintreurnicht there are two ways of using Liquibase Neo4j:

1. using the fat JAR, that shades the JDBC connector
2. using the regular JAR, that does not shade anything

Option 1 is mostly meant for end users, such as Liquibase CLI users, who can then just drop the fat JAR in the plugin folder of their Liquibase installation and start writing Liquibase change sets for Neo4j.

Option 2 is for application and library authors. In that context, regular dependency resolution applies.

It seems that:

- you were either not aware that option 2 existed, in which case I need to document that better
- or that option 2 does not apply to your situation, in which case I will need more information.

**Comment by fbiville** [comment]
@martintreurnicht does option 2 work for you?

**Comment by martintreurnicht** [comment]
> @martintreurnicht does option 2 work for you?

Hi, we've recently upgraded some of our neo4j libraries for liquibase, after migration it seems like the issue no longer affects us.

**Comment by GrahamLea** [comment]
For anyone ending up here via Google and wondering how to do what @fbiville was suggesting re. not using the `neo4j-jdbc` fat jar, you need to exclude `neo4j-jdbc-driver` from Liquibase/Liquigraph (or whatever else is bringing it in), and then include `neo4j-jdbc-bolt` separately. Example:
```
        <dependency>
            <groupId>org.liquigraph</groupId>
            <artifactId>liquigraph-core</artifactId>
            <version>4.0.4</version>
            <exclusions>
                <exclusion>
                    <groupId>org.neo4j</groupId>
                    <artifactId>neo4j-jdbc-driver</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <!-- Used by Liquigraph, but the one in its POM includes a shaded Jackson -->
            <groupId>org.neo4j</groupId>
            <artifactId>neo4j-jdbc-bolt</artifactId>
            <version>4.0.5</version>
        </dependency>
```

**Comment by fbiville** [comment]
@GrahamLea thanks for the extra details
Let me know if you need help migrating from Liquigraph to Liquibase: https://www.liquigraph.org/migration-to-liquibase/

**Comment by GrahamLea** [comment]
Thanks! It's on the TODO list, just hasn't reached the top yet. 😊

**Pull request closed without merging**
