### PR TITLE
Update benchkit implementation with new requirements

### PR DESCRIPTION
**Pull request by bigmontz**
Benchkit specs were update with a new swagger file that defines new
enums and a new endpoint for checking if the backend is ready.

Some adjustments are also needed related to backend configuration and
docker orchestration.

### CODE REVIEW

**Comment by michael-simons** [comment]
What's the point of the additional docker file not using Spring Boots default mechanism?

**Comment by bigmontz** [comment]
> What's the point of the additional docker file not using Spring Boots default mechanism?

Benchkit builds the backend image using the Dockerfile and this is defined in the docker-compose file, [see](https://github.com/neo4j-drivers/benchkit/pull/2/files#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3R22-R24). We can not remove this property by extending the docker compose file.

Because of this, we need a Dockerfile in the repository.

[More info about benchkit setup.](https://github.com/neo4j-drivers/benchkit/pull/2/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R45)

**Review by michael-simons — CHANGES_REQUESTED** [review]
Got ya. 

But than we should follow best practices as declared here

https://docs.spring.io/spring-boot/docs/current/reference/html/container-images.html#container-images.dockerfiles

Please update the Dockerfile accordingly

And after that, adapt the instructions here:
https://github.com/neo4j/neo4j-jdbc/blob/5a33d76a159630b8f2618e0b84c91fc00239e78b/CONTRIBUTING.adoc#benchkit-support

Thank you!

**Comment by bigmontz** [comment]
Changes on the Dockerfile in place. I keep the mvn as their own step since the maven image doesn't contain jre.

**Review by michael-simons — APPROVED** [review]
Nice stuff, thank you.

**Pull request merged**
